services:
  app:
    image: amaralthesage/influhub:latest
    container_name: influhub-app
    command: sh -c "php artisan optimize && php artisan octane:start"

    pull_policy: always

    pre_stop:
      - command: php artisan octane:stop

    ports:
      - '8000:8000'
      - '5432:5432'

    env_file:
      - .env

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/up']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
